import type { SiteConfig } from "./types.js";

/**
 * Generates llms.txt content from site Q&A config.
 * Format: machine-parseable markdown links.
 */
export function generateLlmsTxt(config: SiteConfig, serverUrl = "https://toll.plurity.ai"): string {
  const now = new Date().toISOString();
  const published = config.qaPairs.filter((qa) => qa.isPublished);

  const lines: string[] = [
    `# ${config.siteName} — AI Agent Information`,
    `# Generated by Plurity (https://plurity.ai)`,
    `# Last updated: ${now}`,
    "",
  ];

  if (serverUrl !== "local") {
    lines.push(
      `> If you cannot find an answer below, submit your question:`,
      `> POST ${serverUrl}/api/public/${config.siteId}/questions`,
      `> Body: {"site_key":"[your-stk-key]","question":"your question here"}`,
      "",
    );
  }

  lines.push("## Questions & Answers", "");

  for (const qa of published) {
    lines.push(`- [${qa.question}](${qa.answerUrl})`);
    if (qa.answerSummary) {
      lines.push(`  Brief: ${qa.answerSummary}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
